name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Clasp
        run: npm install -g @google/clasp

      - name: Authenticate Clasp
        # Sử dụng cat << 'EOF' thay vì echo để tránh lỗi định dạng JSON
        run: |
          cat << 'EOF' > ~/.clasprc.json
          ${{ secrets.CLASP_CREDENTIALS }}
          EOF

      - name: Push to GAS
        run: clasp push -f
